# Generated by Django 5.2.17 on 2026-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trace_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='chunk_overlap',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='chunk_size',
            field=models.PositiveIntegerField(default=1600),
        ),
    ]
